
import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0";

export default function Protected() {
    const { user, error, isLoading } = useUser();
    return (
        <div className={styles.container}>
            <Head>
                <title>Protected page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className={styles.main}>
                <h1 className={styles.title}>Welcome to a protected page.</h1>
                <p className={styles.description}>Here are your details</p>
                <div >
                    {user && (
                        <p>Welcome
                            <span >{user.name}</span>
                        </p>
                    )}
                    {!user && (
                        <p>You are Not signed In, Please Sign In to view the Secret Pages.</p>
                    )}
                </div>
            </main>
        </div>
    );
}